server:
  hostname: 0.0.0.0
  port: 8080
  type: port
storage:
  username: postgres
  password: 1234
  host: localhost
  port: 5432
  database_name: account
  url: postgres://postgres:1234@localhost:5432/account
